### ISSUE TITLE
Custom type generating not working

### ISSUE THREAD

**Issue by ribbon-xx** [apollographql/apollo-android#2721]
Apollo version: 2.4.1
Build gradle: 4.1.0
Gradle wrapper: 6.5-all

build.gradle:
```
android {}
apollo {
    useSemanticNaming = true
    generateKotlinModels = true
    customTypeMapping = [
            "Date" : "java.util.Date"
    ]
}
```
CustomType.java as attachment.

Adapter
```
val sdfISO8601 = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss")
        val dateCustomTypeAdapter = object : CustomTypeAdapter<Date> {
            override fun decode(value: CustomTypeValue<*>): Date {
                return try {
                    sdfISO8601.parse(value.value.toString())
                } catch (e: ParseException) {
                    throw RuntimeException(e)
                }
            }

            override fun encode(value: Date): CustomTypeValue<*> {
                return CustomTypeValue.GraphQLString(sdfISO8601.format(value))
            }
        }
```

Usage of Adapter:
```
apolloClient = ApolloClient.builder()
            .serverUrl(BASE_URL)
            .okHttpClient(okHttpClient)
            .normalizedCache(normalizedCacheFactory, cacheKeyResolver)
            .addCustomTypeAdapter(CustomType.DATE, dateCustomTypeAdapter)
            .build()
```

Could you please tell me how to make apollo generates the right CustomType file?

![Screen Shot 2020-11-02 at 21 40 44](https://user-images.githubusercontent.com/457409/97880710-14e5e080-1d54-11eb-9053-40c8c9026e48.png)

**Comment by martinbonnin** [comment]
Hi 👋 ! Looks like you're generating Kotlin models but are looking at a Java file so something's wrong there. Either set `generateKotlinModels = false` or use `CustomType.kt`

**Comment by ribbon-xx** [comment]
> Hi 👋 ! Looks like you're generating Kotlin models but are looking at a Java file so something's wrong there. Either set `generateKotlinModels = false` or use `CustomType.kt`

Thanks for your reply!
I think my problem is I cannot import CustomType.kt, I've searched all the project's folders but only CustomType.java.
Could you tell me how can I have CustomType.kt, thanks you so much

**Comment by ribbon-xx** [comment]
I've made a clean and rebuild task, CustomType.kt is generated but it does not contain the key in build.gradle file, please take a look at the 
![Uploading Screen Shot 2020-11-03 at 01.03.55.png…]()
attachment image

**Comment by martinbonnin** [comment]
That might be a cache issue. Maybe try "Invalidate Caches/Restart" in the "File" menu of Android Studio? 

Or from the command line: `./gradlew clean generateApolloSources --no-build-cache`

**Comment by ribbon-xx** [comment]
> That might be a cache issue. Maybe try "Invalidate Caches/Restart" in the "File" menu of Android Studio?
> 
> You can also try this from the command line: `./gradlew clean generateApolloSources --no-build-cache`

I'm doing Invalidate Caches & Restart, I'll be back immediately and update the result on this comment

**Comment by ribbon-xx** [comment]
I've downloaded a example from github: https://github.com/BoD/apollo-graphql-android-sample
build.gradle:
```
apollo {
    generateKotlinModels.set(true)
    customTypeMapping.set(mapOf(
        "Date" to "java.util.Date"
    ))
}
```
CustomType.kt:
```
package com.example.graphqlsample.queries.type

import com.apollographql.apollo.api.ScalarType
import kotlin.String

enum class CustomType : ScalarType {
  ID {
    override fun typeName(): String = "ID"

    override fun className(): String = "kotlin.String"
  }
}
```
Adapter is the same in apollo's guide: https://www.apollographql.com/docs/android/essentials/custom-scalar-types/

Someone please help on it, I can't build project because of this issue

**Comment by martinbonnin** [comment]
Hi @ribbon-xx ! the [apollo-graphql-android-sample](https://github.com/BoD/apollo-graphql-android-sample) schema doesn't contain a custom `Date` scalar, which is why it's not getting generated. We will throw an error in the future if that happens (see [this issue]'(https://github.com/apollographql/apollo-android/issues/2486#issuecomment-720999302)).

More generally, types that are also not generated if they're not used in any query. 
Can you copy/paste the build error you have? Maybe it's something else?

**Comment by martinbonnin** [comment]
@ribbon-xx Were you able to find what was the issue? Anything else I can help with?

**Comment by dryst0** [comment]
Hi!

I first encountered this issue in [https://github.com/aoudiamoncef/apollo-client-maven-plugin/issues/40](url) and thought that this was a problem in the plugin itself.

It was suggested to me that maybe there is an issue with Apollo compiler itself.

Using the plugin's maven configuration, I defined the following customTypeMap for my scalars:

```
<customTypeMap>
    <DateTime>java.time.LocalDateTime</DateTime>
    <GeoJSONString>java.lang.String</GeoJSONString>
</customTypeMap>
```

Here's a snippet of my schema.json file
```
{
...
},
{
    "kind": "SCALAR",
    "name": "GeoJSONString",
    "description": "A GeoJSON formatted String.\n\n\nCurrently only supports Point GeoJSON type.\n\ne.g.\n\n\"{\n    \"type\": \"Point\",\n    \"coordinates\": [125.6, 10.1]\n}\"\n\n\nSupport for LineString GeoJSON type is under development.\n\n\n\nPlease see https://geojson.org for more info.",
    "fields": null,
    "inputFields": null,
    "interfaces": null,
    "enumValues": null,
     "possibleTypes": null
},
{
...
}
```

I also tried providing a CustomTypeAdapter but still didn't include the GeoJSONString CustomTypeMap in CustomType.java file upon generation.

```
public enum CustomType implements ScalarType {
  DATETIME {
    @Override
    public String typeName() {
      return "DateTime";
    }

    @Override
    public String className() {
      return "java.time.LocalDateTime";
    }
  },

  ID {
    @Override
    public String typeName() {
      return "ID";
    }

    @Override
    public String className() {
      return "java.lang.String";
    }
  }
}
```

I have also added the custom type adapters to my apolloClient

```
ApolloClient apolloClient = ApolloClient.builder().serverUrl(impressionsEndpoint)
                .addCustomTypeAdapter(CustomType.DATETIME, dateTimeAdapter)
                .addCustomTypeAdapter(CustomType.GEOJSONSTRING, geojsonCustomTypeAdapter).okHttpClient(client).build();
```

Only `CustomType.DATETIME` was included in the auto-generated class file. `CustomType.GEOJSONSTRING` doesn't exist and therefore my build is failing.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project common: Compilation failure
[ERROR] <redacted> cannot find symbol
[ERROR]   symbol:   variable GEOJSONSTRING
[ERROR]   location: class m.m.m.graphql.client.type.CustomType
```

Please advise if I did something wrong on my end or recommend how should I be able to fix it.

**Comment by martinbonnin** [comment]
@dryst0 Double checking: is your `GEOJSONSTRING ` scalar used by any query? By default, we only generate for the scalars that are used, which might explain why you're not seeing it.

**Comment by dryst0** [comment]
> @dryst0 Double checking: is your `GEOJSONSTRING ` scalar used by any query? By default, we only generate for the scalars that are used, which might explain why you're not seeing it.

Yes, in fact, the java files that were generated from `.graphql` files produced the following snippet in the generated code
```
...
@Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          writer.writeInt("id", id);
          if (startDateTime.defined) {
            writer.writeCustom("startDateTime", m.m.m.graphql.client.type.CustomType.DATETIME, startDateTime.value != null ? startDateTime.value : null);
          }
          if (endDateTime.defined) {
            writer.writeCustom("endDateTime", m.m.m.graphql.client.type.CustomType.DATETIME, endDateTime.value != null ? endDateTime.value : null);
          }
          if (radius.defined) {
            writer.writeInt("radius", radius.value);
          }
          writer.writeCustom("location", m.m.mgraphql.client.type.CustomType.GEOJSONSTRING, location);
        }
      };
    }
  }
...
```

This is one of the sample query in the `.graphql`
```
query SampleQuery($id: Int!, $startDateTime: DateTime, $endDateTime: DateTime, $radius: Int, $location: GeoJSONString!) {
  sampleQuery1(campaignId: $id, startDateTime: $startDateTime, endDateTime: $endDateTime) {
    field1
    field2
    field3
  }
  sampleQuery2(campaignId: $id, location: $location, radius: $radius, startDateTime: $startDateTime, endDateTime: $endDateTime) {
    field1
    field2
    field3
  }
}
```

**Comment by martinbonnin** [comment]
Thanks for sending this, I'll look into it. Maybe the custom scalar isn't detected in variables. That seems unlikely but that might be an option. Do you know what version of the `apollo-android` compiler is used?

**Comment by dryst0** [comment]
> Thanks for sending this, I'll look into it. Maybe the custom scalar isn't detected in variables. That seems unlikely but that might be an option. Do you know what version of the `apollo-android` compiler is used?

I'm not really sure what `apollo-android` was used by the plugin but its using the following apollo dependencies:

- com.apollographql.apollo » apollo-compiler 2.3.1
- com.apollographql.apollo » apollo-api-jvm 2.3.1

Hope it helps.

Do you have any recommendations as to how I should workaround this issue while you're investigating?

Also, thank you very much for the quick response.

**Comment by martinbonnin** [comment]
> Maybe the custom scalar isn't detected in variables
I just checked and custom scalars [are correctly detected](https://github.com/martinbonnin/apollo-android/commit/ac4fe360dbc718dbc057cfd9867fdd0b3d2bf4f2) there so it must be something else.

>com.apollographql.apollo » apollo-compiler 2.3.1

Thanks, that seems recent enough. It's worth trying with `2.4.5` but I'm not sure how to do this from the maven plugin.

 Is there any chance you could put a small reproducer project somewhere? Or send it to martin at apollographql.com?

**Comment by dryst0** [comment]
> I just checked and custom scalars are correctly detected there so it must be something else.

On my end, only the `CustomType.DateTime` scalar was parsed and detected and the only noticeable difference is that DateTime uses a proper PascalCase while GeoJSONString contains an all-caps in-between. It seems far-fetched but maybe a sanitation issue?

> It's worth trying with 2.4.5

I'll try and use this version instead of the included version and see if it fixes.

> Is there any chance you could put a small reproducer project somewhere?

I'll update and send you a sample project if updating the compiler didn't work.

**Comment by martinbonnin** [comment]
> only noticeable difference is that DateTime uses a proper PascalCase while GeoJSONString contains an all-caps in-between. It seems far-fetched but maybe a sanitation issue?

I tried using the exact same `GeoJSONString` name but it still generates the custom scalar: https://github.com/martinbonnin/apollo-android/commit/434fec5de0a6663c5797ea6da93715c34a19f367. So it's something else. Maybe something in the gradle plugin or elsewhere. A reproducer project will help a ton if you can send one!

**Comment by dryst0** [comment]
> I tried using the exact same GeoJSONString name but it still generates the custom scalar: martinbonnin@434fec5. So it's something else. Maybe something in the gradle plugin or elsewhere. A reproducer project will help a ton if you can send one!

Well, at least that assumption is out of the way now.

On a different note, I tried using the plugin and overriding both apollo dependencies to point to `2.4.5` but the plugin threw an exception:

`[ERROR] Failed to execute goal com.github.sparow199:apollo-client-maven-plugin:3.3.1:generate (mobads-impressions) on project common: Execution of goal com.github.sparow199:apollo-client-maven-plugin:3.3.1:generate failed: An API incompatibility was encountered while executing com.github.sparow199:apollo-client-maven-plugin:3.3.1:generate: java.lang.NoSuchMethodError: com.apollographql.apollo.compiler.DefaultPackageNameProvider.<init>(Ljava/util/Collection;Ljava/io/File;Ljava/lang/String;)V`

I'll let you know once I've pushed a sample project into my repo.

**Comment by martinbonnin** [comment]
> I guess there were some breaking changes when upgrading from 2.3.1 to 2.4.5

Looks like it. The `apollo-compiler` API is not really considered public API since it has very few consumers (gradle plugin and maven plugin, I'm not aware of any others). Maybe it'd make sense to start enforcing semver there at some point.

> I'll let you know once I've pushed a sample project into my repo.

Awesome, thanks!

**Comment by dryst0** [comment]
It looks like I've found the reason why `CustomType.GEOJSONSTRING` wasn't included in the generation of CustomType.java while I was doing the sample project.

```
...
<plugin>
	<groupId>com.github.sparow199</groupId>
	<artifactId>apollo-client-maven-plugin</artifactId>
	<version>3.3.1</version>
	<executions>
		<execution>
			<id>schema1</id>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<sourceDirName>${project.basedir}/src/main/graphql/m/m/m/client/schema1</sourceDirName>
				<rootPackageName>m.m.m.graphql.client</rootPackageName>
				<introspectionFile>${project.basedir}/src/main/graphql/m/m/m/client/schema1/schema.json</introspectionFile>
				**<outputDirectory>${project.build.directory}/generated-sources/graphql-client</outputDirectory>**
				<customTypeMap>
					<GeoJSONString>java.lang.String</GeoJSONString>
					<DateTime>java.time.LocalDateTime</DateTime>
				</customTypeMap>
			</configuration>
		</execution>
		<execution>
			<id>schema2</id>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<sourceDirName>${project.basedir}/src/main/graphql/m/m/m/client/schema2</sourceDirName>
				<rootPackageName>m.m.m.graphql.client</rootPackageName>
				<introspectionFile>${project.basedir}/src/main/graphql/m/m/m/client/schema2/schema.json</introspectionFile>
				**<outputDirectory>${project.build.directory}/generated-sources/graphql-client</outputDirectory>**
				<customTypeMap>
					<DateTime>java.time.LocalDateTime</DateTime>
					<GeoJSONString>java.lang.String</GeoJSONString>
				</customTypeMap>
			</configuration>
		</execution>
		<execution>
			<id>schema3</id>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<sourceDirName>${project.basedir}/src/main/graphql/m/m/m/client/schema3</sourceDirName>
				<rootPackageName>m.m.m.graphql.client</rootPackageName>
				<introspectionFile>${project.basedir}/src/main/graphql/m/m/m/client/schema3/schema.json</introspectionFile>
				**<outputDirectory>${project.build.directory}/generated-sources/graphql-client</outputDirectory>**
				<customTypeMap>
					<DateTime>java.time.LocalDateTime</DateTime>
					<GeoJSONString>java.lang.String</GeoJSONString>
				</customTypeMap>
			</configuration>
		</execution>
	</executions>
</plugin>
...
```

As shown by my example above, I configured the plugin to execute 3 times on individual namespaces with different graphQL schemas but they all write their output on the same directory. It appears that with each execution it overwrites the CustomType.java and since the other namespaces doesn't use `CustomType.GEOJSONSTRING` it didn't get generated. This was inline to what you've [said](https://github.com/apollographql/apollo-android/issues/2721#issuecomment-730236136) earlier that if the CustomType isn't used in any of the queries, it also won't be included in the auto-generated code.

Bottomline, I misunderstood how the apollo code generation plugin works

Anyway, thanks for all the help and assistance in solving my happy problem. Hope this post-mortem report will help someone not to make the same mistake as I did.

**Comment by martinbonnin** [comment]
@dryst0 nice, thanks a lot for the follow up.

@ribbon-xx, I'll close this issue for assuming that it was a similar problem. Please leave a message if you want me to reopen it.
