### ISSUE TITLE
Apollo GraphQL client fails on startup due to coroutines version incompatibility

### ISSUE THREAD

**Issue by Sayid25** [apollographql/apollo-android#6608]
### Version

Apollo Version 4.3.1

### Summary

Component	                        Version
Apollo Kotlin Runtime	          4.3.1
kotlinx-coroutines-core	  1.10.2
Kotlin	                                  2.2.0
Spring Boot	                          3.5.3

```
apollo {
    service("service") {
        packageName.set("com.respiroc.ecomtools.graphql")
        generateOptionalOperationVariables.set(false)
        // Shopify has non-standard scalars in graphql schema, this avoids Any type for fields in generated classes
        mapScalarToKotlinString("UnsignedInt64")
        mapScalarToKotlinString("Decimal")
        mapScalarToKotlinString("Money")
        mapScalarToKotlinString("URL")
        mapScalarToKotlinString("HTML")
    }
}
```

When upgrading to Apollo Kotlin 4.1.1 or newer, my application fails at runtime with a NoSuchMethodError. The issue stems from Apollo's internal usage of CoroutineDispatcher.limitedParallelism$default(...), which appears to be incompatible with kotlinx-coroutines-core:1.10.2.

Everything works fine on Apollo 4.1.0, but breaks from 4.1.1 onwards.

### Logs

2025-07-01T10:26:58.257+05:00 ERROR 7974 --- [lTaskExecutor-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.respiroc.customerservice.CacheWarmupConfig.onApplicationEvent(org.springframework.boot.context.event.ApplicationReadyEvent)

```
java.lang.NoSuchMethodError: 'kotlinx.coroutines.CoroutineDispatcher kotlinx.coroutines.CoroutineDispatcher.limitedParallelism$default(kotlinx.coroutines.CoroutineDispatcher, int, java.lang.String, int, java.lang.Object)'
	at com.apollographql.apollo.network.ws.WebSocketNetworkTransport.<init>(WebSocketNetworkTransport.kt:89) ~[apollo-runtime-jvm-4.3.1.jar:4.3.1]
	at com.apollographql.apollo.network.ws.WebSocketNetworkTransport.<init>(WebSocketNetworkTransport.kt) ~[apollo-runtime-jvm-4.3.1.jar:4.3.1]
	at com.apollographql.apollo.network.ws.WebSocketNetworkTransport$Builder.build(WebSocketNetworkTransport.kt:442) ~[apollo-runtime-jvm-4.3.1.jar:4.3.1]
	at com.apollographql.apollo.ApolloClient.<init>(ApolloClient.kt:180) ~[apollo-runtime-jvm-4.3.1.jar:4.3.1]
	at com.apollographql.apollo.ApolloClient.<init>(ApolloClient.kt) ~[apollo-runtime-jvm-4.3.1.jar:4.3.1]
	at com.apollographql.apollo.ApolloClient$Builder.build(ApolloClient.kt:976) ~[apollo-runtime-jvm-4.3.1.jar:4.3.1]
	at com.respiroc.customerservice.Shopify.getApolloClient(Shopify.kt:80) ~[main/:na]
	at com.respiroc.customerservice.Shopify.access$getApolloClient(Shopify.kt:35) ~[main/:na]
	at com.respiroc.customerservice.Shopify$getActiveProductsWithInventory$response$1.invokeSuspend(Shopify.kt:2852) ~[main/:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith$$$capture(ContinuationImpl.kt:33) ~[kotlin-stdlib-2.2.0.jar:2.2.0-release-294]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt) ~[kotlin-stdlib-2.2.0.jar:2.2.0-release-294]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at com.respiroc.customerservice.Shopify.getActiveProductsWithInventory(Shopify.kt:2852) ~[main/:na]
	at com.respiroc.customerservice.Shopify.getAllProductsInventoryQtyMoreThan0(Shopify.kt:168) ~[main/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:565) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359) ~[spring-aop-6.2.8.jar:6.2.8]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:724) ~[spring-aop-6.2.8.jar:6.2.8]
	at com.respiroc.customerservice.Shopify$$SpringCGLIB$$0.getAllProductsInventoryQtyMoreThan0(<generated>) ~[main/:na]
	at com.respiroc.customerservice.ProductInfoForAIService.getProductInfo(CustomerService.kt:1839) ~[main/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:565) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359) ~[spring-aop-6.2.8.jar:6.2.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.2.8.jar:6.2.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.2.8.jar:6.2.8]
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:55) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:431) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.cache.interceptor.CacheAspectSupport.evaluate(CacheAspectSupport.java:601) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:448) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:410) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:65) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.2.8.jar:6.2.8]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728) ~[spring-aop-6.2.8.jar:6.2.8]
	at com.respiroc.customerservice.ProductInfoForAIService$$SpringCGLIB$$0.getProductInfo(<generated>) ~[main/:na]
	at com.respiroc.customerservice.CacheWarmupConfig.onApplicationEvent(CustomerService.kt:1939) ~[main/:na]
	at com.respiroc.customerservice.CacheWarmupConfig.onApplicationEvent(CustomerService.kt:1924) ~[main/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:565) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359) ~[spring-aop-6.2.8.jar:6.2.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.2.8.jar:6.2.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.2.8.jar:6.2.8]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:114) ~[spring-aop-6.2.8.jar:6.2.8]
	at org.springframework.security.concurrent.DelegatingSecurityContextCallable.call(DelegatingSecurityContextCallable.java:96) ~[spring-security-core-6.5.1.jar:6.5.1]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:328) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1447) ~[na:na]
```

**Comment by Sayid25** [comment]
Thank you for reviewing this.

I ran ./gradlew <module>:dependencies to verify the versions being used. I’m currently using the latest stable version of Spring Boot (3.5.3), and here’s a relevant excerpt from the output:

\--- org.springframework.boot:spring-boot-starter-test -> 3.5.3
     +--- org.springframework.boot:spring-boot-starter:3.5.3 (*)
     +--- org.springframework.boot:spring-boot-test:3.5.3
     |    +--- org.springframework.boot:spring-boot:3.5.3 (*)
     |    \--- org.springframework:spring-test:6.2.8
     |         \--- org.springframework:spring-core:6.2.8 (*)
     +--- org.springframework.boot:spring-boot-test-autoconfigure:3.5.3
     |    +--- org.springframework.boot:spring-boot:3.5.3 (*)
     |    +--- org.springframework.boot:spring-boot-test:3.5.3 (*)
     |    \--- org.springframework.boot:spring-boot-autoconfigure:3.5.3 (*) 

For coroutines, the version being used in my project is:

+--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.10.2 -> 1.8.1
|         +--- org.jetbrains:annotations:23.0.0
|         +--- org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.8.1
|         |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.8.1 (c)
|         |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1 -> 1.10.2 (c)
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.9.21 -> 2.2.0 (*)
+--- com.apollographql.apollo:apollo-runtime:4.3.1
|    \--- com.apollographql.apollo:apollo-runtime-jvm:4.3.1
|         +--- com.squareup.okhttp3:okhttp:4.12.0
|         |    +--- com.squareup.okio:okio:3.6.0 -> 3.9.0
|         |    |    \--- com.squareup.okio:okio-jvm:3.9.0
|         |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.9.21 -> 2.2.0 (*)
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21 -> 2.2.0
|         |         +--- org.jetbrains.kotlin:kotlin-stdlib:2.2.0 (*)
|         |         \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.2.0
|         |              \--- org.jetbrains.kotlin:kotlin-stdlib:2.2.0 (*)
|         +--- com.apollographql.apollo:apollo-api:4.3.1
|         |    \--- com.apollographql.apollo:apollo-api-jvm:4.3.1
|         |         +--- com.squareup.okio:okio:3.9.0 (*)
|         |         +--- com.benasher44:uuid:0.8.2
|         |         |    \--- com.benasher44:uuid-jvm:0.8.2
|         |         |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.9.20 -> 2.2.0 (*)
|         |         \--- com.apollographql.apollo:apollo-annotations:4.3.1
|         |              \--- com.apollographql.apollo:apollo-annotations-jvm:4.3.1
|         |                   +--- org.jetbrains.kotlin:kotlin-stdlib -> 2.2.0 (*)
|         |                   +--- org.jetbrains.kotlin:kotlin-stdlib-common -> 2.2.0
|         |                   |    \--- org.jetbrains.kotlin:kotlin-stdlib:2.2.0 (*)
|         |                   +--- org.jetbrains.kotlin:kotlin-stdlib:2.0.0 -> 2.2.0 (c)
|         |                   \--- org.jetbrains.kotlin:kotlin-stdlib-common:2.0.0 -> 2.2.0 (c)
|         +--- com.apollographql.apollo:apollo-mpp-utils:4.3.1
|         |    \--- com.apollographql.apollo:apollo-mpp-utils-jvm:4.3.1
|         |         \--- com.apollographql.apollo:apollo-annotations:4.3.1 (*)
|         +--- com.squareup.okio:okio:3.9.0 (*)
|         +--- com.benasher44:uuid:0.8.2 (*)
|         +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0 -> 1.10.2 (*)
|         \--- org.jetbrains.kotlinx:atomicfu:0.26.0
|              \--- org.jetbrains.kotlinx:atomicfu-jvm:0.26.0
|                   \--- org.jetbrains.kotlin:kotlin-stdlib:{prefer 2.0.21} -> 2.2.0 (*)

**Comment by Sayid25** [comment]
adding this below config in build.gradle.kts solved the issue.

configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.jetbrains.kotlinx" && requested.name.contains("coroutines")) {
            useVersion("1.10.2")
        }
    }
}
