### ISSUE TITLE
parentType.getFields is not a function

### ISSUE THREAD

**Issue by hzsweers** [apollographql/apollo-android#521]
Seeing this issue after updating to 0.3.1, worked fine on 0.3.0.

The schema I'm working with is just the github graphql schema, can share a snippet of the query if need be

```
TypeError: parentType.getFields is not a function
    at Compiler.resolveFields (/Users/pandanomic/dev/android/personal/CatchUp/app/build/apollo-codegen/node_modules/apollo-codegen/src/compilation.js:305:35)
    at Compiler.resolveFields (/Users/pandanomic/dev/android/personal/CatchUp/app/build/apollo-codegen/node_modules/apollo-codegen/src/compilation.js:330:67)
    at Compiler.resolveFields (/Users/pandanomic/dev/android/personal/CatchUp/app/build/apollo-codegen/node_modules/apollo-codegen/src/compilation.js:330:67)
    at Compiler.compileOperation (/Users/pandanomic/dev/android/personal/CatchUp/app/build/apollo-codegen/node_modules/apollo-codegen/src/compilation.js:143:29)
    at /Users/pandanomic/dev/android/personal/CatchUp/app/build/apollo-codegen/node_modules/apollo-codegen/src/compilation.js:59:49
    at Array.forEach (native)
    at compileToIR (/Users/pandanomic/dev/android/personal/CatchUp/app/build/apollo-codegen/node_modules/apollo-codegen/src/compilation.js:58:23)
    at generate (/Users/pandanomic/dev/android/personal/CatchUp/app/build/apollo-codegen/node_modules/apollo-codegen/src/generate.js:29:19)
    at Object.handler (/Users/pandanomic/dev/android/personal/CatchUp/app/build/apollo-codegen/node_modules/apollo-codegen/src/cli.js:161:9)
    at Object.self.runCommand (/Users/pandanomic/dev/android/personal/CatchUp/app/build/apollo-codegen/node_modules/yargs/lib/command.js:233:22)
```

**Comment by sav007** [comment]
Please, try to clean and rebuild. We saw the same issue with @kassim clean and rebuild should help

**Comment by hzsweers** [comment]
Still there even after cleaning :/

**Comment by kassim** [comment]
The clean+rebuild didn't help me. Maybe that was bad communication on my part. The clean got the build of the sample working, not my project.

The only thing that got it working was reverting to a previous commit of apollo-android. Even then I had to skip failing tests to get the build to finish.

**Comment by kassim** [comment]
requires an update to codegen v 0.12.9 as mentioned https://github.com/apollographql/apollo-codegen/issues/141
