### ISSUE TITLE
Issue with latest AGP and JAVA 11

### ISSUE THREAD

**Issue by GauravP123** [apollographql/apollo-android#3338]
Hi,
We are using `apollo v 2.4.5`. Recently we have upgraded to the latest android studio and AGP. As the latest version needs Java 11 when we set java 11 and try to build the project we are getting the following error. The same code is working with JAVA 1.8 n older AGP

Error 
`graphql/api/type/CustomType.java:22: error: invalid method declaration; return type required`

CustomType is basically implements  `com.apollographql.apollo.api.ScalarType`

 ```
  CustomType() {
            super();
        }
```

**Comment by martinbonnin** [comment]
Hi 👋 . Thanks for reaching out! I'll dig into this. Quick verification: would using kotlin models be an option? 

```
apollo {
  generateKotlinModels.set(true)
}
```

I'm pretty sure that would remove this error

**Comment by GauravP123** [comment]
Its already present

**Comment by GauravP123** [comment]
its coming when i am trying to make release build 

`/Users/gaurav/project/app/build/tmp/kapt3/stubs/appRelease/com/app/graphql/type/CustomType.java:22: error: invalid method declaration; return type required
        CustomType() {
        ^`

**Comment by martinbonnin** [comment]
I see, it's in kapt stubs 🤔 . That's interesting. Can you share your .graphql query and schema?

**Comment by GauravP123** [comment]
`.graphql` as in? coz these are custom types.

error class look like 
```
package com.app.graphql.bayonet.type;

import com.apollographql.apollo.api.ScalarType;
import kotlin.String;

@kotlin.Metadata(mv = {1, 1, 15}, bv = {1, 0, 3}, k = 1, d1 = {"\u0000\u0010\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\u0018\u0002\n\u0002\b\u0003\b\u0086\u0001\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u00012\u00020\u0002B\u0007\b\u0002\u00a2\u0006\u0002\u0010\u0003j\u0002\b\u0004\u00a8\u0006\u0005"}, d2 = {"/type/CustomType;", "", "Lcom/apollographql/apollo/api/ScalarType;", "(Ljava/lang/String;I)V", "ID", "app_AppRelease"})
public enum CustomType implements com.apollographql.apollo.api.ScalarType {
    /*public static final*/ ID /* = new @kotlin.Metadata(mv = {1, 1, 15}, bv = {1, 0, 3}, k = 1, d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000e\n\u0002\b\u0002\b\u00c6\u0001\u0018\u00002\u00020\u0001J\b\u0010\u0002\u001a\u00020\u0003H\u0016J\b\u0010\u0004\u001a\u00020\u0003H\u0016\u00a8\u0006\u0005"}, d2 = {"/type/CustomType$ID;", "/type/CustomType;", "className", "", "typeName", "app_appRelease"}) ID() */ /*enum*/  {
        
        @org.jetbrains.annotations.NotNull
        @java.lang.Override
        public java.lang.String typeName() {
            return null;
        }
        
        @org.jetbrains.annotations.NotNull
        @java.lang.Override
        public java.lang.String className() {
            return null;
        }
        
        CustomType() {
            super();
        }
    };
    
    CustomType() {
    }
}
```

**Comment by martinbonnin** [comment]
> .graphql as in? coz these are custom types

Oh my..  Sorry I'm doing too many things at the same time. You're right 👍 , there's no query involved there. 

> kt class look like

Thanks! This looks like a very reasonable `CustomType` class. Actually it's very similar to the one we have in the tutorial. I'll try to reproduce later today see if there's anything obvious. If you have a reproducer on your side somewhere, that'd be super helpful too.

**Comment by martinbonnin** [comment]
Tried reproducing the issue but the stubs are way different:

```java

package com.example.type;

import java.lang.System;

@kotlin.Metadata(mv = {1, 5, 1}, k = 1, d1 = {"\u0000\u0010\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\u0018\u0002\n\u0002\b\u0004\b\u0086\u0001\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u00012\u00020\u0002B\u0007\b\u0002\u00a2\u0006\u0002\u0010\u0003j\u0002\b\u0004j\u0002\b\u0005\u00a8\u0006\u0006"}, d2 = {"Lcom/example/type/CustomType;", "", "Lcom/apollographql/apollo/api/ScalarType;", "(Ljava/lang/String;I)V", "DATE", "ID", "app_release"})
public enum CustomType implements com.apollographql.apollo.api.ScalarType {
    /*public static final*/ DATE /* = new @kotlin.Metadata(mv = {1, 5, 1}, k = 1, d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000e\n\u0002\b\u0002\b\u00c6\u0001\u0018\u00002\u00020\u0001J\b\u0010\u0002\u001a\u00020\u0003H\u0016J\b\u0010\u0004\u001a\u00020\u0003H\u0016\u00a8\u0006\u0005"}, d2 = {"Lcom/example/type/CustomType$DATE;", "Lcom/example/type/CustomType;", "className", "", "typeName", "app_release"}) DATE(){
    
    DATE() {
        super();
    }
    
    @org.jetbrains.annotations.NotNull()
    @java.lang.Override()
    public java.lang.String typeName() {
        return null;
    }
    
    @org.jetbrains.annotations.NotNull()
    @java.lang.Override()
    public java.lang.String className() {
        return null;
    }
} */,
    /*public static final*/ ID /* = new @kotlin.Metadata(mv = {1, 5, 1}, k = 1, d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000e\n\u0002\b\u0002\b\u00c6\u0001\u0018\u00002\u00020\u0001J\b\u0010\u0002\u001a\u00020\u0003H\u0016J\b\u0010\u0004\u001a\u00020\u0003H\u0016\u00a8\u0006\u0005"}, d2 = {"Lcom/example/type/CustomType$ID;", "Lcom/example/type/CustomType;", "className", "", "typeName", "app_release"}) ID(){
    
    ID() {
        super();
    }
    
    @org.jetbrains.annotations.NotNull()
    @java.lang.Override()
    public java.lang.String typeName() {
        return null;
    }
    
    @org.jetbrains.annotations.NotNull()
    @java.lang.Override()
    public java.lang.String className() {
        return null;
    }
} */;
    
    CustomType() {
    }
}
```
(notice the comments)

I'm using:
* Kotlin 1.5.20
* AGP 7.1.0-alpha11
* OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)

Can you share your versions?

**Comment by GauravP123** [comment]
-  ext.kotlin_version = '1.3.50'
-  AGP 7.0.1
-  openjdk version "16.0.2" 2021-07-20

**Comment by martinbonnin** [comment]
Thanks for providing this. You bumped into this bug: https://youtrack.jetbrains.com/issue/KT-33052

You'll need to upgrade your Kotlin version. It's not 100% clear from that ticket but looks like `1.3.61` might have the fix although 1.4.x definitely sounds like a safer bet.

**Comment by martinbonnin** [comment]
Let me know if I can close this one. There's not much we can do on Apollo Android side.

**Comment by GauravP123** [comment]
sure i will try today or max tom and let you know

**Comment by GauravP123** [comment]
After updating kotlin getting some other issue. but that error no longer exists. Thanks for the quick help
