### ISSUE TITLE
CustomTypeAdapter - Kotlin errors version 0.5.0

### ISSUE THREAD

**Issue by Luna2442** [apollographql/apollo-android#905]
This code works fine with version 0.4.4, but I had started using 0.5.0 and Kotlin threw some compilation errors. Notably I see the difference is the location of the interface `import com.apollographql.apollo.CustomTypeAdapter` vs. `import com.apollographql.apollo.response.CustomTypeAdapter`. 

```
        class DateTypeAdapter : CustomTypeAdapter<Date> {

            val df = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.US)

            init {
                df.timeZone = TimeZone.getTimeZone("UTC")
            }

            override fun decode(value: String): Date {
                try {
                    return df.parse(value)
                } catch (e : ParseException) {
                    throw e
                }

            }

            override fun encode(value: Date): String {
                return df.format(value)
            }
        }
```

Compilation Errors:
1. Class DateTypeAdapter is not abstract and does not implement abstract member
` class DateTypeAdapter : CustomTypeAdapter<Date> {`
2. decode overrides nothing
```
            override fun decode(value: String): Date {
                try {
                    return df.parse(value)
                } catch (e : ParseException) {
                    throw e
                }
```
3. return type is 'String' which is not a subtype of overridden.
```
            override fun encode(value: Date): String {
                return df.format(value)
            }
```

**Comment by sav007** [comment]
Please check: https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/response/CustomTypeAdapter.java

the signature has changed:
```
public interface CustomTypeAdapter<T> {

  T decode(@Nonnull CustomTypeValue value);

  @Nonnull CustomTypeValue encode(@Nonnull T value);
}
```

**Comment by omerfarukyilmaz** [comment]
For anyone looking for Kotlin syntax:

```
private val GRAPHQL_DATE_FORMAT = SimpleDateFormat("EEE MMM dd yyyy HH:mm:ss Z", Locale.US)

val customTypeAdapterDate = object : CustomTypeAdapter<Date> {

    override fun encode(value: Date): CustomTypeValue<*> {
        return CustomTypeValue.GraphQLString(GRAPHQL_DATE_FORMAT.format(value))
    }

    override fun decode(value: CustomTypeValue<*>): Date? {
        return try {
            GRAPHQL_DATE_FORMAT.parse(value.value.toString())
        } catch (e: ParseException) {
            return null
        }
    }

}
```

For ApolloClient.builder()
```
.addCustomTypeAdapter(CustomType.DATETIME, customTypeAdapterDate)
```

I return an optional Date? and null cause I have some fields from the backend that return empty dates. So I did not prefer to go the ```throw new RuntimeException(e)``` way found in README.md. Since it's Kotlin, I handle my optionals with ease 🙂.

// Anyone can correct me if I'm wrong. Still a beginner in Kotlin.
