### ISSUE TITLE
Make the project compile with Android gradle plugin version 3.2.1

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#1141]
Using master, `./gradlew build` fails with `No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android`. This is the same issue as [this one](https://github.com/google/filament/issues/15#issuecomment-426259512).

This can be workaround'd by tricking the old apollo plugin into thinking there is a mips toolchain as described in the other issue: ` mkdir -p $ANDROID_HOME/ndk-bundle/toolchains/mips64el-linux-android/prebuilt/linux-x86_64`

Nonetheless, it would be nice to update the apollo plugin version but this currently fails with: 

    /home/martin/git/apollo-android/apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/CodegenGenerationTaskCommandArgsBuilder.java:136: error: <anonymous com.apollographql.apollo.gradle.CodegenGenerationTaskCommandArgsBuilder$2> is not abstract and does not override abstract method test(File) in Predicate
      schemaQueryMap.put(normalizedSchemaFileName, new ApolloCodegenIRArgs(f, FluentIterable.from(files).filter(new Predicate<File>() {

So I guess a classpath issue somewhere....

**Comment by sav007** [comment]
Should we close it now?

**Comment by martinbonnin** [comment]
Yup :thumsup:
